language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
node_js:
 - "6.10"

install:
  - npm install -g bower

script:
  - dotnet restore src/Rng/
  - dotnet publish src/Rng/ -r ubuntu.14.04-x64 -o deployment/build/rng -c Release
  - dotnet restore src/Hasher/
  - dotnet publish src/Hasher/ -r ubuntu.14.04-x64 -o deployment/build/hasher -c Release
  - dotnet restore src/Worker/
  - dotnet publish src/Worker/ -r ubuntu.14.04-x64 -o deployment/build/worker -c Release
  - dotnet restore src/WebUI/
  - dotnet publish src/WebUI/ -r ubuntu.14.04-x64 -o deployment/build/webui -c Release
  - export REPO_HASH=richardcase/dockercoinsnetcore-hasher
  - export REPO_RNG=richardcase/dockercoinsnetcore-rng
  - export REPO_WEB=richardcase/dockercoinsnetcore-webui
  - export REPO_WORK=richardcase/dockercoinsnetcore-worker
  - export VERSION=`cat ./VERSION`
  - export BUILDDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - echo $VERSION
  - echo $BUILDDATE
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - cd deployment/
  - docker build -f  Dockerfile-rng -t $REPO_RNG:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:$TAG
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:$VERSION
  - docker push $REPO_RNG

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
