language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
node_js:
 - "6.10"
services:
  - docker

install:
  - npm install -g bower

script:
  #- docker run -it --rm -v $(pwd):/sln --workdir /sln microsoft/dotnet:1.1.0-sdk-projectjson sh ./build-rng.sh
  #- docker run -it --rm -v $(pwd):/sln --workdir /sln microsoft/dotnet:1.1.0-sdk-projectjson sh ./build-hasher.sh
  #- docker run -it --rm -v $(pwd):/sln --workdir /sln microsoft/dotnet:1.1.0-sdk-projectjson sh ./build-worker.sh
  #- docker run -it --rm -v $(pwd):/sln --workdir /sln microsoft/dotnet:1.1.0-sdk-projectjson sh ./build-webui.sh
  - dotnet restore src/Rng/
  - dotnet publish src/Rng/ -o deployment/build/rng -c Release
  - dotnet restore src/Hasher/
  - dotnet publish src/Hasher/ -o deployment/build/hasher -c Release
  - dotnet restore src/Worker/
  - dotnet publish src/Worker/ -o deployment/build/worker -c Release
  - dotnet restore src/WebUI/
  - dotnet publish src/WebUI/ -o deployment/build/webui -c Release
  - export REPO_HASH=richardcase/dockercoinsnetcore-hasher
  - export REPO_RNG=richardcase/dockercoinsnetcore-rng
  - export REPO_WEB=richardcase/dockercoinsnetcore-webui
  - export REPO_WORK=richardcase/dockercoinsnetcore-worker
  - export VERSION=`cat ./VERSION`
  - export BUILDDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - echo $VERSION
  - echo $BUILDDATE
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - cd deployment/
  - docker build -f  Dockerfile-rng -t $REPO_RNG:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:$TAG
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_RNG:$COMMIT $REPO_RNG:$VERSION
  - docker push $REPO_RNG
  - docker build -f  Dockerfile-hasher -t $REPO_HASH:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_HASH:$COMMIT $REPO_HASH:$TAG
  - docker tag $REPO_HASH:$COMMIT $REPO_HASH:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_HASH:$COMMIT $REPO_HASH:$VERSION
  - docker push $REPO_HASH
  - docker build -f  Dockerfile-worker -t $REPO_WORK:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_WORK:$COMMIT $REPO_WORK:$TAG
  - docker tag $REPO_WORK:$COMMIT $REPO_WORK:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_WORK:$COMMIT $REPO_WORK:$VERSION
  - docker push $REPO_WORK
  - docker build -f  Dockerfile-webui -t $REPO_WEB:$COMMIT --build-arg BUILD_DATE=$BUILDDATE --build-arg VCS_REF=$COMMIT --build-arg VERSION=$VERSION .
  - docker tag $REPO_WEB:$COMMIT $REPO_WEB:$TAG
  - docker tag $REPO_WEB:$COMMIT $REPO_WEB:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO_WEB:$COMMIT $REPO_WEB:$VERSION
  - docker push $REPO_WEB

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
