FROM scratch

# Add the published artifacts
ADD build/webui /

EXPOSE 8888

ENTRYPOINT ["/Webui"]

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="DockerCoins .NET Core Web UI" \
    org.label-schema.description="Service ti view rate of dockercoin mining" \
    org.label-schema.url="https://github.com/richardcase/dockercoinsnetcore" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/dockercoinsnetcore" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"

