apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
    tier: backend
  name: hasher
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: hasher
    tier: backend