apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
    tier: frontend
  name: webui
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: webui
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer